// <auto-generated />
namespace Vidlib_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class makeDobNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeDobNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202122111454_makeDobNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
